# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2026-01"

[[extensions]]
name = "order-edit"
handle = "order-edit"
type = "ui_extension"
uid = "90b65574-81fb-fc59-bbe8-2134cea9c80971559da8"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.order-status.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#api-access
api_access = true

# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#network-access
network_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "edit_address"
type = "boolean"
name = "Enable Shipping Address Editing"
description = "Allow customers to update their shipping address."
default = true

[[extensions.settings.fields]]
key = "edit_phone"
type = "boolean"
name = "Enable Phone Number Editing"
description = "Allow customers to update their phone number."
default = true

[[extensions.settings.fields]]
key = "apply_discount"
type = "boolean"
name = "Enable Discount Code Application"
description = "Show the section to apply discount codes."
default = true

[[extensions.settings.fields]]
key = "download_invoice"
type = "boolean"
name = "Enable Invoice Download"
description = "Show the section to download the invoice."
default = true

[[extensions.settings.fields]]
key = "delivery_instructions"
type = "boolean"
name = "Enable Delivery Instructions"
description = "Allow customers to update delivery instructions."
default = true


[[extensions.settings.fields]]
key = "edit_order_lines"
type = "boolean"
name = "Enable Order Line Items Editing"
description = "Show the section to edit quantities, replace or remove items."
default = true

[[extensions.settings.fields]]
key = "add_products"
type = "boolean"
name = "Enable Adding More Products"
description = "Allow customers to search and add new products to their order."
default = true
