export const COUNTRY_STATES = {
    IN: [
      { code: "AP", name: "Andhra Pradesh" },
      { code: "AR", name: "Arunachal Pradesh" },
      { code: "AS", name: "Assam" },
      { code: "BR", name: "Bihar" },
      { code: "CT", name: "Chhattisgarh" },
      { code: "GA", name: "Goa" },
      { code: "GJ", name: "Gujarat" },
      { code: "HR", name: "Haryana" },
      { code: "HP", name: "Himachal Pradesh" },
      { code: "JH", name: "Jharkhand" },
      { code: "KA", name: "Karnataka" },
      { code: "KL", name: "Kerala" },
      { code: "MP", name: "Madhya Pradesh" },
      { code: "MH", name: "Maharashtra" },
      { code: "MN", name: "Manipur" },
      { code: "ML", name: "Meghalaya" },
      { code: "MZ", name: "Mizoram" },
      { code: "NL", name: "Nagaland" },
      { code: "OR", name: "Odisha" },
      { code: "PB", name: "Punjab" },
      { code: "RJ", name: "Rajasthan" },
      { code: "SK", name: "Sikkim" },
      { code: "TN", name: "Tamil Nadu" },
      { code: "TG", name: "Telangana" },
      { code: "TR", name: "Tripura" },
      { code: "UP", name: "Uttar Pradesh" },
      { code: "UT", name: "Uttarakhand" },
      { code: "WB", name: "West Bengal" },
      { code: "DL", name: "Delhi" },
      { code: "JK", name: "Jammu & Kashmir" },
      { code: "LA", name: "Ladakh" }
    ],
  
    AE: [
      { code: "AZ", name: "Abu Dhabi" },
      { code: "DU", name: "Dubai" },
      { code: "SH", name: "Sharjah" },
      { code: "AJ", name: "Ajman" },
      { code: "UQ", name: "Umm Al-Quwain" },
      { code: "FU", name: "Fujairah" },
      { code: "RK", name: "Ras Al Khaimah" }
    ],
  
    AT: [
      { code: "1", name: "Burgenland" },
      { code: "2", name: "Kärnten" },
      { code: "3", name: "Niederösterreich" },
      { code: "4", name: "Oberösterreich" },
      { code: "5", name: "Salzburg" },
      { code: "6", name: "Steiermark" },
      { code: "7", name: "Tirol" },
      { code: "8", name: "Vorarlberg" },
      { code: "9", name: "Wien" }
    ],
  
    AU: [
      { code: "NSW", name: "New South Wales" },
      { code: "QLD", name: "Queensland" },
      { code: "SA", name: "South Australia" },
      { code: "TAS", name: "Tasmania" },
      { code: "VIC", name: "Victoria" },
      { code: "WA", name: "Western Australia" },
      { code: "NT", name: "Northern Territory" },
      { code: "ACT", name: "Australian Capital Territory" }
    ],
  
    BE: [],
  
    CA: [
      { code: "AB", name: "Alberta" },
      { code: "BC", name: "British Columbia" },
      { code: "MB", name: "Manitoba" },
      { code: "NB", name: "New Brunswick" },
      { code: "NL", name: "Newfoundland and Labrador" },
      { code: "NS", name: "Nova Scotia" },
      { code: "ON", name: "Ontario" },
      { code: "PE", name: "Prince Edward Island" },
      { code: "QC", name: "Quebec" },
      { code: "SK", name: "Saskatchewan" },
      { code: "NT", name: "Northwest Territories" },
      { code: "NU", name: "Nunavut" },
      { code: "YT", name: "Yukon" }
    ],
  
    CH: [
      { code: "AG", name: "Aargau" },
      { code: "AI", name: "Appenzell Innerrhoden" },
      { code: "AR", name: "Appenzell Ausserrhoden" },
      { code: "BE", name: "Bern" },
      { code: "BL", name: "Basel-Landschaft" },
      { code: "BS", name: "Basel-Stadt" },
      { code: "FR", name: "Fribourg" },
      { code: "GE", name: "Geneva" },
      { code: "GL", name: "Glarus" },
      { code: "GR", name: "Graubünden" },
      { code: "JU", name: "Jura" },
      { code: "LU", name: "Luzern" },
      { code: "NE", name: "Neuchâtel" },
      { code: "NW", name: "Nidwalden" },
      { code: "OW", name: "Obwalden" },
      { code: "SG", name: "St. Gallen" },
      { code: "SH", name: "Schaffhausen" },
      { code: "SO", name: "Solothurn" },
      { code: "SZ", name: "Schwyz" },
      { code: "TG", name: "Thurgau" },
      { code: "TI", name: "Ticino" },
      { code: "UR", name: "Uri" },
      { code: "VD", name: "Vaud" },
      { code: "VS", name: "Valais" },
      { code: "ZG", name: "Zug" },
      { code: "ZH", name: "Zürich" }
    ],
  
    CZ: [
      { code: "PR", name: "Prague" },
      { code: "ST", name: "Central Bohemian" },
      { code: "JC", name: "South Bohemian" },
      { code: "PL", name: "Pilsen" },
      { code: "KA", name: "Karlovy Vary" },
      { code: "US", name: "Ústí nad Labem" },
      { code: "LI", name: "Liberec" },
      { code: "HK", name: "Hradec Králové" },
      { code: "PA", name: "Pardubice" },
      { code: "VY", name: "Vysočina" },
      { code: "JM", name: "South Moravian" },
      { code: "OL", name: "Olomouc" },
      { code: "ZL", name: "Zlín" },
      { code: "MS", name: "Moravian-Silesian" }
    ],
  
    DE: [
      { code: "BW", name: "Baden-Württemberg" },
      { code: "BY", name: "Bavaria" },
      { code: "BE", name: "Berlin" },
      { code: "BB", name: "Brandenburg" },
      { code: "HB", name: "Bremen" },
      { code: "HH", name: "Hamburg" },
      { code: "HE", name: "Hesse" },
      { code: "NI", name: "Lower Saxony" },
      { code: "MV", name: "Mecklenburg-Vorpommern" },
      { code: "NW", name: "North Rhine-Westphalia" },
      { code: "RP", name: "Rhineland-Palatinate" },
      { code: "SL", name: "Saarland" },
      { code: "SN", name: "Saxony" },
      { code: "ST", name: "Saxony-Anhalt" },
      { code: "SH", name: "Schleswig-Holstein" },
      { code: "TH", name: "Thuringia" }
    ],
  
    DK: [
      { code: "H", name: "Hovedstaden" },
      { code: "M", name: "Midtjylland" },
      { code: "N", name: "Nordjylland" },
      { code: "S", name: "Sjælland" },
      { code: "SD", name: "Syddanmark" }
    ],
  
    ES: [
      { code: "AN", name: "Andalusia" },
      { code: "AR", name: "Aragon" },
      { code: "AS", name: "Asturias" },
      { code: "IB", name: "Balearic Islands" },
      { code: "PV", name: "Basque Country" },
      { code: "CN", name: "Canary Islands" },
      { code: "CB", name: "Cantabria" },
      { code: "CL", name: "Castile and León" },
      { code: "CM", name: "Castilla-La Mancha" },
      { code: "CT", name: "Catalonia" },
      { code: "EX", name: "Extremadura" },
      { code: "GA", name: "Galicia" },
      { code: "MD", name: "Madrid" },
      { code: "MC", name: "Murcia" },
      { code: "NC", name: "Navarre" },
      { code: "RI", name: "La Rioja" },
      { code: "VC", name: "Valencian Community" }
    ],
  
    FI: [
      { code: "AL", name: "Åland" },
      { code: "ES", name: "South Karelia" },
      { code: "EP", name: "Southern Ostrobothnia" },
      { code: "PS", name: "Southern Savonia" },
      { code: "KA", name: "Kainuu" },
      { code: "KH", name: "Tavastia Proper" },
      { code: "KP", name: "Central Ostrobothnia" },
      { code: "KS", name: "Central Finland" },
      { code: "KY", name: "Kymenlaakso" },
      { code: "LL", name: "Lapland" },
      { code: "PI", name: "Pirkanmaa" },
      { code: "PO", name: "Ostrobothnia" },
      { code: "PK", name: "North Karelia" },
      { code: "POH", name: "Northern Ostrobothnia" },
      { code: "PSV", name: "Northern Savonia" },
      { code: "PT", name: "Päijänne Tavastia" },
      { code: "SK", name: "Satakunta" },
      { code: "UU", name: "Uusimaa" },
      { code: "VS", name: "Southwest Finland" }
    ],
  
    FR: [
      { code: "ARA", name: "Auvergne-Rhône-Alpes" },
      { code: "BFC", name: "Bourgogne-Franche-Comté" },
      { code: "BRE", name: "Brittany" },
      { code: "CVL", name: "Centre-Val de Loire" },
      { code: "COR", name: "Corsica" },
      { code: "GES", name: "Grand Est" },
      { code: "HDF", name: "Hauts-de-France" },
      { code: "IDF", name: "Île-de-France" },
      { code: "NOR", name: "Normandy" },
      { code: "NAQ", name: "Nouvelle-Aquitaine" },
      { code: "OCC", name: "Occitanie" },
      { code: "PDL", name: "Pays de la Loire" },
      { code: "PAC", name: "Provence-Alpes-Côte d’Azur" }
    ],
  
    GB: [
      { code: "ENG", name: "England" },
      { code: "NIR", name: "Northern Ireland" },
      { code: "SCT", name: "Scotland" },
      { code: "WLS", name: "Wales" }
    ],
  
    HK: [],
    IE: [],
    IL: [],
  
    IT: [
      { code: "ABR", name: "Abruzzo" },
      { code: "BAS", name: "Basilicata" },
      { code: "CAL", name: "Calabria" },
      { code: "CAM", name: "Campania" },
      { code: "EMR", name: "Emilia-Romagna" },
      { code: "FVG", name: "Friuli Venezia Giulia" },
      { code: "LAZ", name: "Lazio" },
      { code: "LIG", name: "Liguria" },
      { code: "LOM", name: "Lombardy" },
      { code: "MAR", name: "Marche" },
      { code: "MOL", name: "Molise" },
      { code: "PIE", name: "Piedmont" },
      { code: "PUG", name: "Apulia" },
      { code: "SAR", name: "Sardinia" },
      { code: "SIC", name: "Sicily" },
      { code: "TAA", name: "Trentino-South Tyrol" },
      { code: "TOS", name: "Tuscany" },
      { code: "UMB", name: "Umbria" },
      { code: "VDA", name: "Aosta Valley" },
      { code: "VEN", name: "Veneto" }
    ],
  
    JP: [
      { code: "01", name: "Hokkaido" },
      { code: "02", name: "Aomori" },
      { code: "03", name: "Iwate" },
      { code: "04", name: "Miyagi" },
      { code: "05", name: "Akita" },
      { code: "06", name: "Yamagata" },
      { code: "07", name: "Fukushima" },
      { code: "08", name: "Ibaraki" },
      { code: "09", name: "Tochigi" },
      { code: "10", name: "Gunma" },
      { code: "11", name: "Saitama" },
      { code: "12", name: "Chiba" },
      { code: "13", name: "Tokyo" },
      { code: "14", name: "Kanagawa" },
      { code: "15", name: "Niigata" },
      { code: "16", name: "Toyama" },
      { code: "17", name: "Ishikawa" },
      { code: "18", name: "Fukui" },
      { code: "19", name: "Yamanashi" },
      { code: "20", name: "Nagano" },
      { code: "21", name: "Gifu" },
      { code: "22", name: "Shizuoka" },
      { code: "23", name: "Aichi" },
      { code: "24", name: "Mie" },
      { code: "25", name: "Shiga" },
      { code: "26", name: "Kyoto" },
      { code: "27", name: "Osaka" },
      { code: "28", name: "Hyogo" },
      { code: "29", name: "Nara" },
      { code: "30", name: "Wakayama" },
      { code: "31", name: "Tottori" },
      { code: "32", name: "Shimane" },
      { code: "33", name: "Okayama" },
      { code: "34", name: "Hiroshima" },
      { code: "35", name: "Yamaguchi" },
      { code: "36", name: "Tokushima" },
      { code: "37", name: "Kagawa" },
      { code: "38", name: "Ehime" },
      { code: "39", name: "Kochi" },
      { code: "40", name: "Fukuoka" },
      { code: "41", name: "Saga" },
      { code: "42", name: "Nagasaki" },
      { code: "43", name: "Kumamoto" },
      { code: "44", name: "Oita" },
      { code: "45", name: "Miyazaki" },
      { code: "46", name: "Kagoshima" },
      { code: "47", name: "Okinawa" }
    ],
  
    KR: [
      { code: "11", name: "Seoul" },
      { code: "26", name: "Busan" },
      { code: "27", name: "Daegu" },
      { code: "28", name: "Incheon" },
      { code: "29", name: "Gwangju" },
      { code: "30", name: "Daejeon" },
      { code: "31", name: "Ulsan" },
      { code: "50", name: "Sejong" },
      { code: "41", name: "Gyeonggi" },
      { code: "42", name: "Gangwon" },
      { code: "43", name: "Chungbuk" },
      { code: "44", name: "Chungnam" },
      { code: "45", name: "Jeonbuk" },
      { code: "46", name: "Jeonnam" },
      { code: "47", name: "Gyeongbuk" },
      { code: "48", name: "Gyeongnam" },
      { code: "49", name: "Jeju" }
    ],
  
    MY: [
      { code: "JH", name: "Johor" },
      { code: "KD", name: "Kedah" },
      { code: "KT", name: "Kelantan" },
      { code: "ML", name: "Malacca" },
      { code: "NS", name: "Negeri Sembilan" },
      { code: "PH", name: "Pahang" },
      { code: "PG", name: "Penang" },
      { code: "PK", name: "Perak" },
      { code: "PL", name: "Perlis" },
      { code: "SB", name: "Sabah" },
      { code: "SW", name: "Sarawak" },
      { code: "SL", name: "Selangor" },
      { code: "TG", name: "Terengganu" },
      { code: "KL", name: "Kuala Lumpur" },
      { code: "LB", name: "Labuan" },
      { code: "PJ", name: "Putrajaya" }
    ],
  
    NL: [
      { code: "DR", name: "Drenthe" },
      { code: "FL", name: "Flevoland" },
      { code: "FR", name: "Friesland" },
      { code: "GE", name: "Gelderland" },
      { code: "GR", name: "Groningen" },
      { code: "LI", name: "Limburg" },
      { code: "NB", name: "North Brabant" },
      { code: "NH", name: "North Holland" },
      { code: "OV", name: "Overijssel" },
      { code: "ZH", name: "South Holland" },
      { code: "UT", name: "Utrecht" },
      { code: "ZE", name: "Zeeland" }
    ],
  
    NO: [
      { code: "03", name: "Oslo" },
      { code: "11", name: "Rogaland" },
      { code: "15", name: "Møre og Romsdal" },
      { code: "18", name: "Nordland" },
      { code: "30", name: "Viken" },
      { code: "34", name: "Innlandet" },
      { code: "38", name: "Vestfold og Telemark" },
      { code: "42", name: "Agder" },
      { code: "46", name: "Vestland" },
      { code: "50", name: "Trøndelag" },
      { code: "54", name: "Troms og Finnmark" }
    ],
  
    NZ: [
      { code: "AUK", name: "Auckland" },
      { code: "BOP", name: "Bay of Plenty" },
      { code: "CAN", name: "Canterbury" },
      { code: "GIS", name: "Gisborne" },
      { code: "HKB", name: "Hawke's Bay" },
      { code: "MWT", name: "Manawatū-Whanganui" },
      { code: "MBH", name: "Marlborough" },
      { code: "NSN", name: "Nelson" },
      { code: "NTL", name: "Northland" },
      { code: "OTA", name: "Otago" },
      { code: "STL", name: "Southland" },
      { code: "TKI", name: "Taranaki" },
      { code: "TAS", name: "Tasman" },
      { code: "WKO", name: "Waikato" },
      { code: "WGN", name: "Wellington" },
      { code: "WTC", name: "West Coast" }
    ],
  
    PL: [
      { code: "DS", name: "Lower Silesian" },
      { code: "KP", name: "Kuyavian-Pomeranian" },
      { code: "LU", name: "Lublin" },
      { code: "LD", name: "Łódź" },
      { code: "MA", name: "Lesser Poland" },
      { code: "MZ", name: "Masovian" },
      { code: "OP", name: "Opole" },
      { code: "PD", name: "Podlaskie" },
      { code: "PK", name: "Subcarpathian" },
      { code: "PM", name: "Pomeranian" },
      { code: "SL", name: "Silesian" },
      { code: "SK", name: "Świętokrzyskie" },
      { code: "WN", name: "Warmian-Masurian" },
      { code: "WP", name: "Greater Poland" },
      { code: "ZP", name: "West Pomeranian" }
    ],
  
    PT: [
      { code: "01", name: "Aveiro" },
      { code: "02", name: "Beja" },
      { code: "03", name: "Braga" },
      { code: "04", name: "Bragança" },
      { code: "05", name: "Castelo Branco" },
      { code: "06", name: "Coimbra" },
      { code: "07", name: "Évora" },
      { code: "08", name: "Faro" },
      { code: "09", name: "Guarda" },
      { code: "10", name: "Leiria" },
      { code: "11", name: "Lisbon" },
      { code: "12", name: "Portalegre" },
      { code: "13", name: "Porto" },
      { code: "14", name: "Santarém" },
      { code: "15", name: "Setúbal" },
      { code: "16", name: "Viana do Castelo" },
      { code: "17", name: "Vila Real" },
      { code: "18", name: "Viseu" },
      { code: "20", name: "Azores" },
      { code: "30", name: "Madeira" }
    ],
  
    SE: [
      { code: "K", name: "Blekinge" },
      { code: "W", name: "Dalarna" },
      { code: "I", name: "Gotland" },
      { code: "X", name: "Gävleborg" },
      { code: "N", name: "Halland" },
      { code: "Z", name: "Jämtland" },
      { code: "F", name: "Jönköping" },
      { code: "H", name: "Kalmar" },
      { code: "G", name: "Kronoberg" },
      { code: "BD", name: "Norrbotten" },
      { code: "T", name: "Örebro" },
      { code: "E", name: "Östergötland" },
      { code: "M", name: "Skåne" },
      { code: "D", name: "Södermanland" },
      { code: "AB", name: "Stockholm" },
      { code: "C", name: "Uppsala" },
      { code: "S", name: "Värmland" },
      { code: "AC", name: "Västerbotten" },
      { code: "Y", name: "Västernorrland" },
      { code: "U", name: "Västmanland" },
      { code: "O", name: "Västra Götaland" }
    ],
  
    SG: [],
  
    US: [
      { code: "AL", name: "Alabama" },
      { code: "AK", name: "Alaska" },
      { code: "AZ", name: "Arizona" },
      { code: "AR", name: "Arkansas" },
      { code: "CA", name: "California" },
      { code: "CO", name: "Colorado" },
      { code: "CT", name: "Connecticut" },
      { code: "DE", name: "Delaware" },
      { code: "FL", name: "Florida" },
      { code: "GA", name: "Georgia" },
      { code: "HI", name: "Hawaii" },
      { code: "ID", name: "Idaho" },
      { code: "IL", name: "Illinois" },
      { code: "IN", name: "Indiana" },
      { code: "IA", name: "Iowa" },
      { code: "KS", name: "Kansas" },
      { code: "KY", name: "Kentucky" },
      { code: "LA", name: "Louisiana" },
      { code: "ME", name: "Maine" },
      { code: "MD", name: "Maryland" },
      { code: "MA", name: "Massachusetts" },
      { code: "MI", name: "Michigan" },
      { code: "MN", name: "Minnesota" },
      { code: "MS", name: "Mississippi" },
      { code: "MO", name: "Missouri" },
      { code: "MT", name: "Montana" },
      { code: "NE", name: "Nebraska" },
      { code: "NV", name: "Nevada" },
      { code: "NH", name: "New Hampshire" },
      { code: "NJ", name: "New Jersey" },
      { code: "NM", name: "New Mexico" },
      { code: "NY", name: "New York" },
      { code: "NC", name: "North Carolina" },
      { code: "ND", name: "North Dakota" },
      { code: "OH", name: "Ohio" },
      { code: "OK", name: "Oklahoma" },
      { code: "OR", name: "Oregon" },
      { code: "PA", name: "Pennsylvania" },
      { code: "RI", name: "Rhode Island" },
      { code: "SC", name: "South Carolina" },
      { code: "SD", name: "South Dakota" },
      { code: "TN", name: "Tennessee" },
      { code: "TX", name: "Texas" },
      { code: "UT", name: "Utah" },
      { code: "VT", name: "Vermont" },
      { code: "VA", name: "Virginia" },
      { code: "WA", name: "Washington" },
      { code: "WV", name: "West Virginia" },
      { code: "WI", name: "Wisconsin" },
      { code: "WY", name: "Wyoming" }
    ]
  };
  

  export default COUNTRY_STATES; 